const List<String> commonMedicines = [
  // Common Generics
  'acetaminophen',
  'aspirin',
  'ibuprofen',
  'paracetamol',
  'atorvastatin',
  'metformin',
  'amoxicillin',
  'lisinopril',
  'levothyroxine',
  'amlodipine',
  'metoprolol',
  'albuterol',
  'omeprazole',
  'losartan',
  'gabapentin',
  'simvastatin',
  'pantoprazole',
  'azithromycin',
  'cetirizine',
  'montelukast',
  'clopidogrel',
  'warfarin',
  'heparin',
  'ciprofloxacin',
  'penicillin',
  'prednisolone',
  'furosemide',
  'sildenafil',
  'ranitidine',
  'escitalopram',
  
  // Common Indian Brands
  'dolo 650',
  'calpol',
  'combiflam',
  'crocin',
  'saridon',
  'disprin',
  'vicks action 500',
  'ibuclin',
  'pantocid',
  'pan-d',
  'telma 40',
  'becosules',
  'limcee',
  'digene',
  'allegra',
  'augmentin',
  'metpure',
  'glycomet',
  'candid',
  'liv 52',
  
  // Common US Brands
  'tylenol',
  'advil',
  'motrin',
  'lipitor',
  'glucophage',
  'zithromax',
  'synthroid',
  'norvasc',
  'lopressor',
  'ventolin',
  'prilosec',
  'cozaar',
  'neurontin',
  'zocor',
  'protonix',
  'coumadin',
  'lasix',
  'viagra',
  'zantac',
  'lexapro'
];
